In [1]:
from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding

Using TensorFlow backend.


In [0]:
# define documents
docs = ['Well done!',
		'Good work',
		'Great effort',
		'nice work',
		'Excellent!',
		'Weak',
		'Poor effort!',
		'not good',
		'poor work',
		'Could have done better.']
# define class labels
labels = array([1,1,1,1,1,0,0,0,0,0])

In [3]:
# integer encode the documents
vocab_size = 50
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)
# pad documents to a max length of 4 words
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)
# define the model
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(256, activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
# summarize the model
print(model.summary())
# fit the model
model.fit(padded_docs, labels, epochs=50)
# evaluate the model
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('Accuracy: %f' % (accuracy*100))

W0817 10:19:29.133260 140284342130560 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0817 10:19:29.190863 140284342130560 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0817 10:19:29.198381 140284342130560 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0817 10:19:29.268959 140284342130560 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0817 10:19:29.292493 140284342130560 deprecation_wrappe

[[11, 49], [38, 40], [40, 48], [35, 40], [1], [9], [49, 48], [24, 38], [49, 40], [8, 37, 49, 36]]
[[11 49  0  0]
 [38 40  0  0]
 [40 48  0  0]
 [35 40  0  0]
 [ 1  0  0  0]
 [ 9  0  0  0]
 [49 48  0  0]
 [24 38  0  0]
 [49 40  0  0]
 [ 8 37 49 36]]
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 4, 8)              400       
_________________________________________________________________
flatten_1 (Flatten)          (None, 32)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 256)               8448      
_________________________________________________________________
dense_2 (Dense)              (None, 128)               32896     
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 129       
Total params: 41,873
Trai

W0817 10:19:29.561578 140284342130560 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Epoch 1/50
10/10 [==============================] - 1s 79ms/step - loss: 0.6934 - acc: 0.5000
Epoch 2/50
10/10 [==============================] - 0s 943us/step - loss: 0.6909 - acc: 0.8000
Epoch 3/50
10/10 [==============================] - 0s 270us/step - loss: 0.6883 - acc: 0.8000
Epoch 4/50
10/10 [==============================] - 0s 471us/step - loss: 0.6856 - acc: 0.8000
Epoch 5/50
10/10 [==============================] - 0s 442us/step - loss: 0.6830 - acc: 0.8000
Epoch 6/50
10/10 [==============================] - 0s 525us/step - loss: 0.6803 - acc: 0.8000
Epoch 7/50
10/10 [==============================] - 0s 441us/step - loss: 0.6774 - acc: 0.8000
Epoch 8/50
10/10 [==============================] - 0s 383us/step - loss: 0.6741 - acc: 0.8000
Epoch 9/50
10/10 [==============================] - 0s 238us/step - loss: 0.6704 - acc: 0.8000
Epoch 10/50
10/10 [==============================] - 0s 260us/step - loss: 0.6663 - acc: 0.8000
Epoch 11/50
10/10 [==============================]

In [16]:
import numpy as np
docs = ['great nice', 'poor effort']
vocab_size = 50
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)
# pad documents to a max length of 4 words
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)
model.predict(padded_docs)

[[40, 35], [49, 48]]
[[40 35  0  0]
 [49 48  0  0]]


array([[0.79063237],
       [0.03938819]], dtype=float32)